module MnemodocServer
  module Tools
    # MCP tool that performs hybrid (semantic + keyword) search over indexed documentation.
    # Embeds the query via Ollama when the mode requires it, then delegates to
    # Search::Hybrid which applies RRF fusion and an optional recency bias before
    # returning the top-K matching chunks.
    class Query
      # Injects the shared config, SQLite store, and Ollama embedder.
      def initialize(@config : Config, @store : Store::SQLite, @embedder : Indexer::Embedder, @qdrant_index : Store::QdrantIndex? = nil)
      end

      Log = ::Log.for("mnemodoc-server.tools.query")

      # Executes a document search.
      # Required arg: "query" (String).
      # Optional args: "top_k" (Integer, defaults to config value), "mode" (hybrid|semantic|keyword).
      # Returns a ToolResult whose structured_content carries "chunks", "total_candidates",
      # "query_time_ms", "mode", and optionally "warning" when the stored embedding model
      # differs from config. The text-block fallback is auto-generated by ToolResult.
      # Ignores the progress reporter (query is not long-running).
      def call(args : Hash(String, JSON::Any), progress : MCP::Progress? = nil) : MCP::ToolResult
        a = MCP::Arguments.new(args)
        query = a.require_string("query")
        top_k = a.int?("top_k").try(&.to_i) || @config.search.top_k
        mode = a.string?("mode") || @config.search.mode

        started_at = Time.monotonic

        query_vec = build_query_vec(query, mode)
        raise MCP::ToolError.new("embedding failed: #{query_vec[:error]}") if query_vec.is_a?(NamedTuple(error: String))

        # Build a per-request search config so mode and top_k from args are applied
        effective_config = SearchConfig.from_yaml("")
        effective_config.mode = mode
        effective_config.top_k = top_k
        effective_config.recency_days = @config.search.recency_days
        effective_config.recency_boost = @config.search.recency_boost
        effective_config.keyword_weight = @config.search.keyword_weight
        results = Search::Hybrid.new(effective_config, @qdrant_index).search(query, query_vec.as(Array(Float32)), @store)
        elapsed_ms = (Time.monotonic - started_at).total_milliseconds.to_i

        chunks_data = results.first(top_k).map do |result|
          JSON::Any.new({
            "file"           => JSON::Any.new(result.chunk.file_path),
            "heading"        => result.chunk.heading.try { |heading| JSON::Any.new(heading) } || JSON::Any.new(nil.as(String?)),
            "parent_heading" => result.chunk.parent_heading.try { |heading| JSON::Any.new(heading) } || JSON::Any.new(nil.as(String?)),
            "content"        => JSON::Any.new(result.chunk.content),
            "score"          => JSON::Any.new(result.score.round(4)),
          } of String => JSON::Any)
        end

        structured = {
          "chunks"           => JSON::Any.new(chunks_data),
          "total_candidates" => JSON::Any.new(@store.chunk_count),
          "query_time_ms"    => JSON::Any.new(elapsed_ms),
          "mode"             => JSON::Any.new(mode),
        } of String => JSON::Any

        # Warn when the stored embedding model differs from the active config;
        # results will silently score near-zero because vector dimensions differ.
        # The warnings array shape is shared with the advisory wrapper (Task 5).
        if @store.model_mismatch?(@config.ollama.model)
          stored = @store.embedding_model || "unknown"
          current = @config.ollama.model
          warning = "index built with model '#{stored}'; current config uses '#{current}' — re-index required"
          Log.warn { warning }
          structured["warnings"] = JSON::Any.new([JSON::Any.new(warning)])
        end

        MCP::ToolResult.new(structured_content: JSON::Any.new(structured))
      end

      # Returns the query embedding for semantic/hybrid modes, or an empty vector
      # for keyword-only mode (no Ollama call needed). Returns an error tuple on
      # embedding failure.
      private def build_query_vec(query : String, mode : String) : Array(Float32) | NamedTuple(error: String)
        return [] of Float32 if mode == "keyword"
        @embedder.embed_batch([query]).first
      rescue ex : Indexer::EmbedderError
        {error: ex.message || "unknown embedding error"}
      end
    end
  end
end
