module MnemodocServer
  module Tools
    # MCP tool that performs hybrid (semantic + keyword) search over indexed documentation.
    # Embeds the query via Ollama when the mode requires it, then delegates to
    # Search::Hybrid which applies RRF fusion and an optional recency bias before
    # returning the top-K matching chunks.
    class Query
      # Injects the shared config, SQLite store, and Ollama embedder.
      def initialize(@config : Config, @store : Store::SQLite, @embedder : Indexer::Embedder, @qdrant_index : Store::QdrantIndex? = nil)
      end

      Log = ::Log.for("mnemodoc-server.tools.query")

      # Upper bound on a client-supplied top_k. High enough that no legitimate
      # request meets it, low enough that the ×4 over-fetch downstream stays
      # well inside Int32 — the point where an absurd value used to overflow.
      MAX_TOP_K = 1000

      MODES = {"hybrid", "semantic", "keyword"}

      # Executes a document search.
      # Required arg: "query" (String).
      # Optional args: "top_k" (Integer, defaults to config value), "mode" (hybrid|semantic|keyword).
      # Returns a ToolResult whose structured_content carries "chunks", "total_candidates",
      # "query_time_ms", "mode", and optionally "warning" when the stored embedding model
      # differs from config. The text-block fallback is auto-generated by ToolResult.
      # Ignores the progress reporter (query is not long-running).
      def call(args : Hash(String, JSON::Any), progress : MCP::Progress? = nil) : MCP::ToolResult
        a = MCP::Arguments.new(args)
        query = a.require_string("query")
        # Both of these come from a client we do not control, and both used to
        # reach the search unchecked: a negative top_k raised ArgumentError out
        # of Array#first, a huge one overflowed the Int32 over-fetch, and zero
        # returned nothing at all without a word. A mode outside the set matched
        # neither branch of the fusion, so the answer was an empty result that
        # looked like an empty index — after paying for the embedding.
        top_k = (a.int?("top_k").try(&.to_i) || @config.search.top_k).clamp(1, MAX_TOP_K)
        mode = a.string?("mode") || @config.search.mode
        unless MODES.includes?(mode)
          raise MCP::ToolError.new("mode must be one of #{MODES.join(", ")} (got #{mode.inspect})")
        end

        refuse_stale_vectors!(mode)

        started_at = Time.instant

        query_vec = build_query_vec(query, mode)
        raise MCP::ToolError.new("embedding failed: #{query_vec[:error]}") if query_vec.is_a?(NamedTuple(error: String))

        # Build a per-request search config so mode and top_k from args are applied
        effective_config = SearchConfig.from_yaml("")
        effective_config.mode = mode
        effective_config.top_k = top_k
        effective_config.recency_days = @config.search.recency_days
        effective_config.recency_boost = @config.search.recency_boost
        effective_config.keyword_weight = @config.search.keyword_weight
        results =
          begin
            Search::Hybrid.new(effective_config, @qdrant_index).search(query, query_vec.as(Array(Float32)), @store)
          rescue ex : Store::EmbeddingDimMismatch
            raise MCP::ToolError.new(ex.message || "embedding dimension mismatch")
          end
        elapsed_ms = (Time.instant - started_at).total_milliseconds.to_i

        # Audit line, at info deliberately: this is the retrieval the whole
        # server exists for, and at debug it was invisible at the default level,
        # so the only way to check how the documentation was actually used was
        # to read the client's own transcript.
        Log.info { "query=#{query.inspect} mode=#{mode} top_k=#{top_k} → #{results.size} results in #{elapsed_ms}ms" }

        # Not truncated again: Hybrid#search already returns at most top_k, and
        # two places enforcing one invariant is one too many.
        chunks_data = results.map do |result|
          JSON::Any.new({
            "file"           => JSON::Any.new(result.chunk.file_path),
            "heading"        => result.chunk.heading.try { |heading| JSON::Any.new(heading) } || JSON::Any.new(nil.as(String?)),
            "parent_heading" => result.chunk.parent_heading.try { |heading| JSON::Any.new(heading) } || JSON::Any.new(nil.as(String?)),
            "content"        => JSON::Any.new(result.chunk.content),
            "score"          => JSON::Any.new(result.score.round(4)),
          } of String => JSON::Any)
        end

        structured = {
          "chunks"           => JSON::Any.new(chunks_data),
          "total_candidates" => JSON::Any.new(@store.chunk_count),
          "query_time_ms"    => JSON::Any.new(elapsed_ms),
          "mode"             => JSON::Any.new(mode),
        } of String => JSON::Any

        # Only reachable in keyword mode now: the vector modes refuse outright
        # above. A keyword answer is honest under a model change — it simply
        # carries no semantic signal, and says so.
        if @store.model_mismatch?(@config.ollama.model)
          stored = @store.embedding_model || "unknown"
          current = @config.ollama.model
          warning = "index built with model '#{stored}'; current config uses '#{current}' — " \
                    "this answer carries the keyword signal only; re-index to restore semantic search"
          Log.warn { warning }
          structured["warnings"] = JSON::Any.new([JSON::Any.new(warning)])
        end

        MCP::ToolResult.new(structured_content: JSON::Any.new(structured))
      end

      # Refuses the two vector modes when the index was built by another model.
      #
      # This used to return results with a `warnings` entry beside them — a
      # hybrid search backed by nothing but its keyword half, which reads
      # exactly like a working one to whatever asked. Keyword mode is
      # unaffected and still answers, since it never touches a vector.
      private def refuse_stale_vectors!(mode : String) : Nil
        return if mode == "keyword"
        return unless @store.model_mismatch?(@config.ollama.model)
        stored = @store.embedding_model || "unknown"
        raise MCP::ToolError.new(
          "index was built with embedding model '#{stored}' and the configuration now uses " \
          "'#{@config.ollama.model}': the stored vectors cannot be searched with this model. " \
          "Re-index the project, or call this tool with mode=\"keyword\".")
      end

      # Returns the query embedding for semantic/hybrid modes, or an empty vector
      # for keyword-only mode (no Ollama call needed). Returns an error tuple on
      # embedding failure.
      private def build_query_vec(query : String, mode : String) : Array(Float32) | NamedTuple(error: String)
        return [] of Float32 if mode == "keyword"
        @embedder.embed_batch([query]).first
      rescue ex : Indexer::EmbedderError
        {error: ex.message || "unknown embedding error"}
      end
    end
  end
end
