module MnemodocServer
  # Turns an ordinary directory into a MnemoDoc project, and back.
  #
  # This exists because the server is meant to be registered once, globally:
  # nothing on the serving path may create the marker directory, so a single
  # deliberate command has to produce everything a project needs — the marker,
  # a configuration, and the first index.
  module Project
    # Directories conventionally holding project documentation, in the order
    # they are offered. Only those that actually exist are written to the
    # generated configuration: a path that is not there would sit in the file as
    # a permanent lie, and would be indistinguishable from one the user removed
    # on purpose.
    DOC_DIRECTORIES = %w(doc docs documentation .claude)

    # Documentation directories present under *root*, as configuration-style
    # relative paths. Falls back to the project root itself when none is found —
    # the only honest default, since every project has one.
    def self.detect_paths(root : String) : Array(String)
      found = DOC_DIRECTORIES
        .select { |name| Dir.exists?(File.join(root, name)) }
        .map { |name| "#{name}/" }
      found.empty? ? ["./"] : found
    end

    # The YAML a fresh project starts from. Deliberately minimal: it carries the
    # detected paths and nothing else, so every other setting keeps tracking the
    # defaults rather than being frozen at the version that generated the file.
    def self.render_config(paths : Array(String)) : String
      String.build do |io|
        io << "# Generated by `mnemodoc-server init`. Edit freely — it is never\n"
        io << "# rewritten unless you pass --force.\n"
        io << "paths:\n"
        paths.each { |path| io << "  - " << path << '\n' }
      end
    end

    # Creates the marker directory and, unless one is already there, the
    # configuration. Returns what was resolved so the caller can report it.
    #
    # An existing configuration is never clobbered without --force: it may be
    # hand-written and carry roles, excludes and thresholds this command knows
    # nothing about.
    def self.initialize_at(root : String, force : Bool = false) : {project: String, config: String, paths: Array(String), config_written: Bool}
      absolute = File.expand_path(root)
      Dir.mkdir_p(File.join(absolute, PROJECT_MARKER))
      write_index_gitignore(File.join(absolute, PROJECT_MARKER))

      config_path = File.join(absolute, ".mnemodoc.yml")
      write = force || !File.exists?(config_path)
      paths = if write
                detected = detect_paths(absolute)
                File.write(config_path, render_config(detected))
                detected
              else
                Config.from_yaml(File.read(config_path)).paths
              end

      {project: File.realpath(absolute), config: config_path, paths: paths, config_written: write}
    end

    # Removes the marker directory, and only that. The configuration is left
    # alone: it is the versionable half of a project, and deleting it would
    # destroy hand-written settings to undo a local, rebuildable index.
    def self.remove_marker(root : String) : Bool
      marker = File.join(File.expand_path(root), PROJECT_MARKER)
      return false unless Dir.exists?(marker)
      FileUtils.rm_rf(marker)
      true
    end

    # Drops a self-ignoring .gitignore in a directory holding index data, so the
    # database, its WAL files, the daemon socket and lock can never be committed
    # by accident. An existing file is left untouched.
    #
    # Shared with `Config#prepare_index_dir!` rather than duplicated: two copies
    # of the same ignore rules would be free to drift, and the one that drifted
    # would leak an index into a repository silently.
    def self.write_index_gitignore(dir : String) : Nil
      gitignore = File.join(dir, ".gitignore")
      return if File.exists?(gitignore)

      File.write(gitignore, <<-IGNORE)
        # Index data for mnemodoc-server — local to each machine, never committed.
        *
        !.gitignore

        IGNORE
    end
  end
end
